# Generated by Django 2.0.7 on 2018-08-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_auto_20180801_1943'),
        ('Orden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_compra', models.CharField(max_length=50, null=True)),
                ('cantidad_material', models.IntegerField(default=0, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Material')),
            ],
        ),
    ]
