# Generated by Django 2.0.7 on 2018-08-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0002_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_material',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
