# Generated by Django 2.0.7 on 2018-07-29 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='bodega',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='codigo_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Material'),
        ),
    ]
