# Generated by Django 2.0.7 on 2018-07-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20180729_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='bodega',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='codigo_material',
        ),
        migrations.AddField(
            model_name='bodega',
            name='nombre_bodega',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='bodega',
            field=models.ManyToManyField(blank=True, to='Inventario.Bodega'),
        ),
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
