# Generated by Django 2.0.7 on 2018-08-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, null=True)),
                ('contraseña', models.CharField(max_length=30, null=True)),
                ('tipo_usuario', models.IntegerField(default=0)),
            ],
        ),
    ]
