# Generated by Django 2.0.7 on 2018-08-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180819_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
